Add controllers
IvanKlimkin/java-shareit pull request #2
Opened 2022-09-09 09:51 UTC by IvanKlimkin

2022-09-09 21:09 UTC, Frilock requested changes
Добрый день, пара незначительных комментариев к работе, в целом все ок. Только я немного не понял, у Вас же это первый спринт по данной работе, почему в ПР не все классы , а часть из них уже была в Main добавлена? Или так и задумано что на ревью не с нуля проект приходит?

По комментарием: кое где видимо забыли убрать лишние зависимости; попросил обособить скобками выражения (во избежание появления ошибок по невнимательности)
другие мелкие правки

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    private final ItemRepository itemRepository;
А зачем тут данное поле? По моему оно не используется, тогда можно его и Required... убрать

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        for (List<Item> userItems : items.values()) {
По моему можно на streamApi переписать items.values.stream....

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +        } else items.get(ownerId).add(item);
Давайте все таки обособим скобками. Это хорошая практика

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        } else throw new Exception(String.format("Пользователь с Email=%s уже существует", user.getEmail()));
Тоже давайте обособим

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +  /*  public User toUser(UserDto userDto) {
Закоментированный код лучше убрать, зачем он Вам? Потом будет не ясно зачем закоментировали, или хотябы TODO ставьте

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    private final UserRepository userRepository;
Для чего тут поле это?

2022-09-09 21:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +                    } else user.setEmail(userDto.getEmail());
Давайте тоже обособим

2022-09-12 08:52 UTC, IvanKlimkin commented
Добрый день, Практикум позволяет склонировать заготовку на проект, собственно оттуда и готовая структура.

2022-09-12 10:51 UTC, Frilock approved these changes
Принято

2022-10-10 08:45 UTC, merged